version: '3'

tasks:
  default:
    cmds:
      - task: run

  run:
    deps:
      - build
    cmds:
      - bin/erasure {{.CLI_ARGS}}
    aliases:
      - r
    silent: true
    method: none

  build:
    cmds:
      - odin build erasure -out=bin/erasure
    aliases:
      - b
    silent: true
    sources:
      - './erasure/**/*.odin'
    generates:
      - bin/erasure

  test:
    cmds:
      - odin test erasure -out=bin/erasure-test
    aliases:
      - t
    silent: true
    sources:
      - './erasure/**/*.odin'
    generates:
      - bin/erasure-test

interval: 250ms
